### ISSUE TITLE
1.20.1 (1.3.0-b2) - Tamer Ability Drains Hunger when Right-Clicking on Most Entities

### ISSUE THREAD

**Issue by Notetaker37** [BlasterM5/ponyorigins#15]
If you pick the Tamer ability, your hunger is affected significantly more than if you didn't. 
Taming (Most) tamable animals works perfectly fine, but with a lot of other entities, including minecarts and boats, the ability meter and by extension your hunger bar are drained unnecessarily!

Below are some entities I experimented this with:

Drains Saturation Unnecessarily:
- Villager
- Piglin
- Iron/Snow Golems
- Cow/Pig/Chicken/Frog/Sniffer
- Horse
- Enderman (hostile and neutral)
- Creeper
- Spider
- Endermite
- Silverfish
- Warden
- Boat/Minecart

Works as Intended: (Or Doesn't Drain Saturation at All)
- Wolf/Cat
- Zombie
- Skeleton
- Phantom
- Zombified Piglin
- Wither
- Armor Stand

> If you pay attention to the hunger bar, the saturation goes down when attempting to trade with villagers, as an example.
> ![javaw_N4tarRrNAE](https://github.com/BlasterM5/ponyorigins/assets/138557927/809105b6-e8fd-40f3-9cce-98ba6cbb4f54)

If it's a limitation of Origins, then oh well- but if it's fixable, that would be great!

**Comment by BlasterM5** [comment]
Oh, this is something I should fix, for sure

**Comment by BlasterM5** [comment]
Fixed in the latest beta?

**Comment by Notetaker37** [comment]
Yes! That was fast, thank you so much! ^^
> ![javaw_vX8btRqUB5](https://github.com/BlasterM5/ponyorigins/assets/138557927/4d0bcc1d-2cce-47ea-8b4b-30e60d7f481f)
