### ISSUE TITLE
(Suggestion) 1.19 Update?

### ISSUE THREAD

**Issue by Notetaker37** [BlasterM5/ponyorigins#16]
If you have the time, backporting the latest version of this mod for 1.19.2 again would be awesome! 

As it stands, the 1.19 version has a couple issues that were fixed in the 1.20 releases, including the log repeating this line every two seconds:
`[Server thread/WARN]: Advancement "ponyorigins:special/interstellar" did not exist, but was referenced in an "origins:advancement" condition.`

As nice as 1.20 is, in my experience troubleshooting custom modpacks, I feel like 1.19.2 has a lot more mod compatibility right now. (For example, just trying to get BetterNether, Create, and Sodium/Indium to all work together in Fabric 1.20.1 is a nightmare! ;~;)
This is such an amazing mod, and I know I and many others would greatly appreciate it!

**Comment by BlasterM5** [comment]
Once I finish fixing the current version and add a new beta, I will start work on the backport. There's quite a few powers I have in 1.20.1 that aren't in 1.19.2, and I have to convert to apugli versions to make it work.

**Comment by BlasterM5** [comment]
Notes for backporting:

All Damage Tags need to be converted to Damage Sources

origins:fire_projectile needs to be converted to apugli:fire_projectile

Check that there aren't other things I am leveraging in 1.20.1 that don't exist in 1.19.2, and use apugli versions of the same methods to backport it.

**Comment by BlasterM5** [comment]
The Back and Forth Port Update is out. LMK if there's issues.
